version: "2"

networks:
  sample:

services:
  go-app-one:
    image: go-app-one
    ports:
      - "8080:8080"

  go-app-two:
    image: go-app-two
    ports:
      - "8081:8080"
  flask-app:
    image: flask-app
    ports:
      - "5000:5000"

  nginx:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf